server:
 port:  8090
spring:
 application:
  name: SpringSecurityJDBCAuthentication
 datasource:
  url: ${DB_URI:jdbc:mysql://localhost:3306/security?serverTimezone=UTC}&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:}
